development:
  sessions:
    default:
      database: platform_auth_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: platform_auth_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: platform_auth
      hosts:
        - localhost:27017
